version: '3.7'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.11
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - 9092:9092
      - 9644:9644
    volumes:
      - redpanda-data:/var/lib/redpanda/data

volumes:
  redpanda-data:
